version: '3'

volumes:
  dsn-redis-data:
    driver: local

  dsn-redis-conf:
    driver: local

services:
  duty-students-notifier:
    image: duty-students-notifier:latest
    network_mode: host
    container_name: duty-students-notifier
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  dsn-redis:
    image: redis:latest
    network_mode: host
    volumes:
      - dsn-redis-data:/var/lib/redis
      - dsn-redis-conf:/usr/local/etc/redis/redis.conf
    restart: always