version: '3.8'

volumes:
  dsn-redis-data:
    driver: local

networks:
  dsn-net:
    driver: bridge

services:
  dsn:
    image: dsn:latest
    container_name: dsn
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - dsn-net
    restart: always

  dsn-redis:
    image: redis:latest
    container_name: dsn-redis
    expose:
      - 6379
    volumes:
      - dsn-redis-data:/data
    networks:
      - dsn-net
    restart: always